/** Shared product error codes for dashboard / server actions. */

export const APP_ERROR_CODE = {
  SIGN_IN_REQUIRED: "sign_in_required",
  NO_WORKSPACE: "no_workspace",
  UNAUTHORIZED: "unauthorized",
  SAVE_FAILED: "save_failed",
  LOAD_FAILED: "load_failed",
  NOT_FOUND: "not_found",
  INVALID_INPUT: "invalid_input",
  NAME_REQUIRED: "name_required",
  NAME_EMPTY: "name_empty",
  NAME_TOO_LONG: "name_too_long",
  TIMEZONE_REQUIRED: "timezone_required",
  TITLE_REQUIRED: "title_required",
  INVALID_DURATION: "invalid_duration",
  INVALID_LOCATION: "invalid_location",
  INVALID_STATUS: "invalid_status",
  SLUG_TOO_SHORT: "slug_too_short",
  SLUG_TAKEN: "slug_taken",
  CAL_KEY_REQUIRED: "cal_key_required",
  CAL_KEY_MISSING: "cal_key_missing",
  CAL_VERIFY_FAILED: "cal_verify_failed",
  CAL_NOT_CONFIGURED: "cal_not_configured",
  CAL_NO_MEETING_TYPES: "cal_no_meeting_types",
  AI_MEETING_TYPE_REQUIRED: "ai_meeting_type_required",
  MEETING_TYPE_NOT_FOUND: "meeting_type_not_found",
  SYNC_FAILED: "sync_failed",
  CREATE_FAILED: "create_failed",
  INVALID_FAQ: "invalid_faq",
  FAQ_LIMIT: "faq_limit",
  FAQ_ITEM_INVALID: "faq_item_invalid",
  FAQ_ITEM_REQUIRED: "faq_item_required",
  INVALID_SUGGESTIONS: "invalid_suggestions",
  SUGGESTION_LIMIT: "suggestion_limit",
  SUGGESTION_INVALID: "suggestion_invalid",
  SUGGESTION_REQUIRED: "suggestion_required",
  MARK_READ_FAILED: "mark_read_failed",
  MARK_ALL_READ_FAILED: "mark_all_read_failed",
  SET_AI_BOOKING_FAILED: "set_ai_booking_failed",
} as const;

export type AppErrorCode = (typeof APP_ERROR_CODE)[keyof typeof APP_ERROR_CODE];
